// Serviços (services listing) copy, transcribed from design-reference's
// PAGES.en.services / PAGES["pt-AO"].services and the isServices render
// block ("design-reference/Idealisa website design (2)/Idealisa Site.dc.html").
//
// This file is self-contained: the "how we work" rows are copied in here
// directly (not imported from lib/content/company.ts) since that file's
// how/essence/culture fields were deliberately dropped from the Sobre Nós
// page and shouldn't be depended on going forward.
import type { Language } from "@/lib/translations";
import type { RoutePageKey } from "@/lib/routes";

export type ServiceGroup = {
  /** Duplicates one of the 4 pillars below — excluded from the rendered grid. */
  dup?: boolean;
  group: string;
  desc?: string;
  outcome?: string;
  items: string[];
  /**
   * Set once this card has its own dedicated page (the eventual silo
   * structure — every "What's included" row should link to its own page).
   * Until then its items keep linking to Contact. Cards without this stay
   * on Contact indefinitely.
   */
  detailRoute?: RoutePageKey;
};

export type ServicePillar = {
  n: string;
  title: string;
  desc: string;
  includes: string[];
  outcome: string;
  /** See ServiceGroup.detailRoute. */
  detailRoute?: RoutePageKey;
};

export type HowWeWorkRow = {
  n: string;
  stage: string;
  body: string;
};

export type ServicesContent = {
  dirKicker: string;
  dirHeading: string;
  dirSub: string;
  includesLabel: string;
  outcomeLabel: string;
  pillars: ServicePillar[];
  dir: ServiceGroup[];
  howHeading: string;
  howSub: string;
  how: HowWeWorkRow[];
  howNote: string;
  contactHeading: string;
  contactNote: string;
  contactCells: { label: string; value: string; href: string }[];
};

const en: ServicesContent = {
  dirKicker: "Our services",
  dirHeading: "Everything we do, in one place",
  dirSub: "Strategy, communication, web, performance and technology: pick the piece you need or the whole direction.",
  includesLabel: "What's included",
  outcomeLabel: "Typical outcome",
  pillars: [
    {
      n: "01",
      title: "Brand Strategy & Branding",
      detailRoute: "brand",
      desc: "We structure brands with clarity, identity and the ability to differentiate, so the business stops competing on price and starts competing on meaning.",
      includes: [
        "Business and brand diagnostics",
        "Market and competitor reading",
        "Positioning and value proposition",
        "Naming, verbal identity and tone of voice",
        "Visual identity direction and brand book",
        "Brand architecture for groups and sub-brands",
        "Rebranding",
        "Brand and communication diagnostics",
        "Strategic marketing planning",
        "Growth and differentiation strategies",
        "Institutional identity and positioning",
      ],
      outcome: "A written positioning the whole company can repeat, and an identity system that survives contact with real campaigns.",
    },
    {
      n: "02",
      title: "Corporate Communication",
      desc: "We structure communication as a strategic asset, to build trust, credibility and institutional value with clients, partners, regulators and staff.",
      includes: [
        "Communication strategy and messaging house",
        "Institutional narrative and leadership voice",
        "Press relations and media training",
        "Internal communication and culture campaigns",
        "Crisis and reputation protocols",
        "Editorial calendars and content governance",
        "Strategic communication and marketing advisory",
        "Institutional communication",
        "Reputation management",
        "Corporate image and positioning advisory",
        "Content strategy",
        "Campaign planning and coordination",
      ],
      outcome: "One voice across every channel, and a plan for what to say when something goes wrong.",
    },
    {
      n: "03",
      title: "Project Management",
      detailRoute: "pm",
      desc: "We transform strategic direction into structured projects, coordinating teams, partners and suppliers and guiding the work towards measurable impact.",
      includes: [
        "Scoping, milestones and budget frameworks",
        "Supplier and partner coordination",
        "Production oversight for campaigns and events",
        "Risk, quality and deadline control",
        "Progress reporting for leadership",
        "Handover and continuity planning",
        "Corporate events",
        "Institutional and commercial campaigns",
        "Brand activations",
        "Social impact projects",
        "Launches and inaugurations",
        "Planning, monitoring and execution supervision",
      ],
      outcome: "Work that ships on the agreed date, at the agreed cost, with one accountable point of contact.",
    },
    {
      n: "04",
      title: "Technology & Digital Solutions",
      desc: "Development and implementation of technology tailored to each project, websites, platforms and the digital presence that carries the brand day to day.",
      includes: [
        "Websites and institutional platforms",
        "E-commerce and booking systems",
        "Digital presence and social management",
        "Performance campaigns and paid media",
        "Analytics, dashboards and reporting",
        "Automation and internal tooling",
        "Website and landing page development",
        "SEO and online presence optimisation",
        "Digital advertising campaigns",
        "Marketing and process automation",
        "Technology solutions tailored to each project",
      ],
      outcome: "A digital presence that reflects the positioning instead of contradicting it, and numbers that prove it works.",
    },
  ],
  dir: [
    {
      dup: true,
      group: "Brand & strategy",
      items: [
        "Brand diagnostics",
        "Brand positioning",
        "Naming",
        "Brand architecture",
        "Visual identity",
        "Brand guidelines",
        "Messaging house",
        "Tone of voice",
        "Strategy workshops",
        "Rebranding",
        "Strategic marketing planning",
        "Growth & differentiation strategies",
        "Institutional identity",
      ],
    },
    {
      dup: true,
      group: "Strategy & project management",
      items: [
        "Digital strategy",
        "Digital campaign planning",
        "Digital marketing review",
        "Media buying",
        "Market research",
        "Digital marketing consulting",
        "Project scoping",
        "Planning & roadmaps",
        "Supplier coordination",
        "Creative direction",
        "Budget management",
        "Launch management",
        "Corporate events",
        "Institutional & commercial campaigns",
        "Brand activations",
        "Social impact projects",
        "Launches & inaugurations",
        "Execution supervision",
      ],
    },
    {
      dup: true,
      group: "Corporate communication",
      items: [
        "Communication strategy",
        "Internal communication",
        "Press relations",
        "Crisis protocol",
        "Spokesperson preparation",
        "Institutional copywriting",
        "Event communication",
        "Annual reports",
        "Stakeholder communication",
        "Reputation management",
        "Institutional communication",
        "Corporate image advisory",
        "Campaign coordination",
      ],
    },
    {
      group: "Design & development",
      desc: "Websites and platforms designed and built to load fast, read clearly and turn visits into enquiries.",
      outcome: "A site the team can update itself, that holds up on a slow connection and a small screen.",
      items: [
        "Website designing",
        "Website development",
        "E-commerce web design",
        "E-commerce web development",
        "WordPress website design",
        "WordPress website development",
        "App development",
        "Responsive website design",
        "Landing pages",
        "Website maintenance",
        "Website migration",
        "Website hosting service",
        "Content management",
      ],
    },
    {
      group: "Web development platforms",
      desc: "The stacks we build on, chosen for the job and the budget, not for fashion.",
      outcome: "A codebase another developer can pick up, on a platform that will still be supported in five years.",
      items: [
        "Shopify website development",
        "WooCommerce website development",
        "Magento website development",
        "Next.js website development",
        "React website development",
        "Vue.js website development",
        "Node website development",
        "Express.js website development",
        "Laravel website development",
        "PHP website development",
        "Python website development",
        "Flutter app development",
        "React Native app development",
      ],
    },
    {
      group: "UX & product design",
      desc: "We design the path a person takes through the product before anyone writes code.",
      outcome: "Screens tested with real users, and a design system the next feature can reuse.",
      items: [
        "UI design",
        "Information architecture",
        "Personas",
        "User experience",
        "User testing",
        "Accessibility",
        "Prototyping",
        "Design systems",
        "Content strategy",
      ],
    },
    {
      group: "Ads management",
      desc: "Paid search and display run as an investment with a reported return, not a monthly fee.",
      outcome: "A cost per enquiry you can plan a budget around, and the data to defend it.",
      items: [
        "Google Ads management",
        "Pay per click (PPC) advertising",
        "Google Display advertising",
        "Google Performance Max ads",
        "Remarketing advertising",
        "Google paid search ads",
        "Bing & Yahoo pay per click",
        "Mobile device advertising",
        "Google Shopping ads / PLAs",
        "Shopping feed management",
        "Programmatic advertising",
        "Multilingual pay per click",
        "Pay per click audit",
        "Amazon advertising",
        "Google Grants",
      ],
    },
    {
      group: "Social media advertising",
      detailRoute: "smm",
      desc: "Presence and paid reach on the platforms your audience actually opens every day.",
      outcome: "Audiences that grow on purpose and creative that earns its place in the feed.",
      items: [
        "Social media management",
        "Facebook advertising",
        "Instagram advertising",
        "LinkedIn advertising",
        "TikTok advertising",
        "YouTube advertising",
        "X (Twitter) advertising",
        "Snapchat advertising",
        "WhatsApp Business",
        "Influencer coordination",
      ],
    },
    {
      group: "Search engine optimisation",
      desc: "We make the business findable at the moment someone is looking for it.",
      outcome: "Steady, unpaid traffic on the searches that matter, and a site technically clean enough to keep it.",
      items: [
        "Search engine optimisation",
        "Keyword research",
        "Search engine optimisation audit",
        "Technical SEO",
        "Content writing",
        "Content marketing",
        "E-commerce optimisation",
        "Local SEO",
        "Browser compatibility",
        "Accessibility implementation",
        "Schema markups",
        "SEO for charity organisations",
      ],
    },
    {
      group: "Tracking & analytics",
      desc: "Measurement set up first, so every decision after it is made on evidence.",
      outcome: "One dashboard leadership trusts, and a clear answer to what each channel returns.",
      items: [
        "Google Analytics setup",
        "Google Tag Manager",
        "Website tracking",
        "Conversion tracking",
        "Conversion optimisation",
        "A/B testing",
        "Heat maps",
        "Reports and dashboards",
        "Cross-platform campaign integration",
        "Microsites",
        "HTML newsletter",
        "Email marketing services",
      ],
    },
    {
      dup: true,
      group: "Technology & solutions",
      items: [
        "Digital solutions consulting",
        "AI integration",
        "Automation workflows",
        "CRM setup",
        "Payment integration",
        "E-commerce integration",
        "Internal tools",
        "Systems integration",
        "Technical documentation",
        "Landing page development",
        "Process automation",
        "Online presence optimisation",
      ],
    },
    {
      group: "AI marketing services",
      desc: "We use AI where it removes work a person should not be doing, qualifying leads, answering the same question, drafting the first version.",
      outcome: "Hours returned to the team every week, and a response time your competitors cannot match by hiring.",
      items: [
        "AI automation",
        "AI chatbot development",
        "AI agent development",
        "AI voice agents / AI receptionists",
        "AI lead generation",
        "AI lead qualification & nurturing",
        "AI appointment booking",
        "AI email marketing & outreach",
        "AI CRM integration & automation",
        "AI website development",
        "AI web app development",
        "AI content creation",
        "AI social media management",
        "AI advertising & ad optimisation",
        "AI SEO, AEO & GEO",
      ],
    },
    {
      group: "Creative & production",
      desc: "The craft layer, design, film, photography and copy produced to the standard the brand claims.",
      outcome: "Campaign assets ready for every format, made once and used everywhere.",
      items: [
        "Graphic design",
        "Logo design",
        "Ad campaign creatives",
        "Rich media and video",
        "Video production",
        "Photography direction",
        "Newsletter design",
        "Exhibition stand design",
        "Leaflet design",
        "Brochures",
        "Copywriting",
      ],
    },
    {
      group: "App development",
      desc: "Mobile and web applications built for the way people actually use a phone here, on a small screen and an uneven connection.",
      outcome: "An application in the stores, instrumented and maintainable, with a roadmap for the next release.",
      items: [
        "Mobile app development",
        "iOS app development",
        "Android app development",
        "Cross-platform apps (Flutter, React Native)",
        "Progressive web apps",
        "Web app development",
        "App UI/UX design",
        "API and backend development",
        "Payment and integration work",
        "App store submission",
        "App maintenance and updates",
        "Analytics and crash reporting",
      ],
    },
  ],
  howHeading: "How we work",
  howSub: "A strategy creates value when it is translated into consistent action. That is why our approach supports the project from understanding the challenge through to its implementation.",
  how: [
    { n: "01", stage: "Diagnosis", body: "Understand the business, context, challenges and opportunities." },
    { n: "02", stage: "Strategic direction", body: "Define priorities, positioning and lines of action." },
    { n: "03", stage: "Structuring", body: "Turn strategic direction into plans, messages, initiatives and resources." },
    { n: "04", stage: "Activation", body: "Coordinate execution with teams, partners and specialised suppliers." },
    { n: "05", stage: "Monitoring", body: "Monitor implementation and ensure consistency throughout the project." },
  ],
  howNote: "When a project requires additional expertise, we coordinate specialised resources in audiovisual production, photography, design, content, campaigns, digital communication, websites and landing pages, SEO and whatever else execution demands.",
  contactHeading: "Contact us",
  contactNote: "Every enquiry is answered within 10 working hours, and within 24 hours over weekends and holidays.",
  contactCells: [
    { label: "WhatsApp", value: "+244 936 499 706", href: "https://wa.me/244936499706" },
    { label: "Email", value: "hello@idealisa.co.ao", href: "mailto:hello@idealisa.co.ao" },
    { label: "Office", value: "Luanda, Angola", href: "https://maps.google.com/?q=Luanda,+Angola" },
  ],
};

const ptAO: ServicesContent = {
  dirKicker: "Os nossos serviços",
  dirHeading: "Tudo o que fazemos, num só lugar",
  dirSub: "Estratégia, comunicação, web, performance e tecnologia: escolha a peça de que precisa ou a direcção completa.",
  includesLabel: "O que inclui",
  outcomeLabel: "Resultado típico",
  pillars: [
    {
      n: "01",
      title: "Estratégia de Marca e Branding",
      detailRoute: "brand",
      desc: "Estruturamos marcas com clareza, identidade e capacidade de diferenciação, para que o negócio deixe de competir pelo preço e passe a competir pelo significado.",
      includes: [
        "Diagnóstico do negócio e da marca",
        "Leitura de mercado e concorrência",
        "Posicionamento e proposta de valor",
        "Naming, identidade verbal e tom de voz",
        "Direcção de identidade visual e manual de marca",
        "Arquitectura de marca para grupos e sub-marcas",
        "Rebranding",
        "Diagnóstico de marca e comunicação",
        "Planeamento estratégico de marketing",
        "Estratégias de crescimento e diferenciação",
        "Identidade e posicionamento institucional",
      ],
      outcome: "Um posicionamento escrito que toda a empresa consegue repetir e um sistema de identidade que resiste a campanhas reais.",
    },
    {
      n: "02",
      title: "Comunicação Corporativa",
      desc: "Estruturamos a comunicação como um activo estratégico, para gerar confiança, credibilidade e valor institucional junto de clientes, parceiros, reguladores e colaboradores.",
      includes: [
        "Estratégia de comunicação e casa de mensagens",
        "Narrativa institucional e voz da liderança",
        "Relações com a imprensa e media training",
        "Comunicação interna e campanhas de cultura",
        "Protocolos de crise e reputação",
        "Calendários editoriais e governação de conteúdos",
        "Assessoria estratégica de comunicação e marketing",
        "Comunicação institucional",
        "Gestão de reputação",
        "Assessoria de imagem e posicionamento corporativo",
        "Estratégia de conteúdos",
        "Planeamento e coordenação de campanhas",
      ],
      outcome: "Uma só voz em todos os canais e um plano para o que dizer quando algo corre mal.",
    },
    {
      n: "03",
      title: "Gestão de Projectos",
      detailRoute: "pm",
      desc: "Transformamos orientações estratégicas em projectos estruturados, coordenando equipas, parceiros e fornecedores e orientando o trabalho para um impacto mensurável.",
      includes: [
        "Âmbito, marcos e enquadramento orçamental",
        "Coordenação de fornecedores e parceiros",
        "Supervisão de produção de campanhas e eventos",
        "Controlo de risco, qualidade e prazos",
        "Relatórios de progresso para a liderança",
        "Transferência e plano de continuidade",
        "Eventos corporativos",
        "Campanhas institucionais e comerciais",
        "Activações de marca",
        "Projectos de impacto social",
        "Lançamentos e inaugurações",
        "Planeamento, monitorização e supervisão de execução",
      ],
      outcome: "Trabalho entregue na data acordada, ao custo acordado, com um único ponto de contacto responsável.",
    },
    {
      n: "04",
      title: "Tecnologia e Soluções Digitais",
      desc: "Desenvolvimento e implementação de tecnologia adequada a cada projecto, sites, plataformas e a presença digital que sustenta a marca no dia-a-dia.",
      includes: [
        "Sites e plataformas institucionais",
        "Comércio electrónico e sistemas de reservas",
        "Presença digital e gestão de redes sociais",
        "Campanhas de performance e media paga",
        "Analítica, dashboards e relatórios",
        "Automação e ferramentas internas",
        "Desenvolvimento de websites e landing pages",
        "SEO e optimização da presença online",
        "Campanhas de publicidade digital",
        "Automação de marketing e processos",
        "Soluções tecnológicas adequadas a cada projecto",
      ],
      outcome: "Uma presença digital que reflecte o posicionamento em vez de o contradizer, e números que o comprovam.",
    },
  ],
  dir: [
    {
      dup: true,
      group: "Marca & estratégia",
      items: [
        "Diagnóstico de marca",
        "Posicionamento de marca",
        "Naming",
        "Arquitectura de marca",
        "Identidade visual",
        "Manual de marca",
        "Casa de mensagens",
        "Tom de voz",
        "Workshops de estratégia",
        "Rebranding",
        "Planeamento estratégico de marketing",
        "Estratégias de crescimento e diferenciação",
        "Identidade institucional",
      ],
    },
    {
      dup: true,
      group: "Estratégia & gestão de projectos",
      items: [
        "Estratégia digital",
        "Planeamento de campanhas digitais",
        "Auditoria de marketing digital",
        "Media buying",
        "Estudos de mercado",
        "Consultoria de marketing digital",
        "Definição de âmbito",
        "Planeamento & roadmaps",
        "Coordenação de fornecedores",
        "Direcção criativa",
        "Gestão de orçamento",
        "Gestão de lançamento",
        "Eventos corporativos",
        "Campanhas institucionais & comerciais",
        "Activações de marca",
        "Projectos de impacto social",
        "Lançamentos & inaugurações",
        "Supervisão de execução",
      ],
    },
    {
      dup: true,
      group: "Comunicação corporativa",
      items: [
        "Estratégia de comunicação",
        "Comunicação interna",
        "Relações com a imprensa",
        "Protocolo de crise",
        "Preparação de porta-vozes",
        "Copywriting institucional",
        "Comunicação de eventos",
        "Relatórios anuais",
        "Comunicação com stakeholders",
        "Gestão de reputação",
        "Comunicação institucional",
        "Assessoria de imagem corporativa",
        "Coordenação de campanhas",
      ],
    },
    {
      group: "Design & desenvolvimento",
      desc: "Websites e plataformas desenhados e construídos para carregar rápido, ler com clareza e transformar visitas em contactos.",
      outcome: "Um site que a equipa consegue actualizar sozinha, que resiste a uma ligação lenta e a um ecrã pequeno.",
      items: [
        "Design de websites",
        "Desenvolvimento web",
        "Design de lojas e-commerce",
        "Desenvolvimento e-commerce",
        "Design WordPress",
        "Desenvolvimento WordPress",
        "Desenvolvimento de apps",
        "Design responsivo",
        "Landing pages",
        "Manutenção de websites",
        "Migração de websites",
        "Alojamento de websites",
        "Gestão de conteúdos",
      ],
    },
    {
      group: "Plataformas de desenvolvimento",
      desc: "As tecnologias em que construímos, escolhidas pelo trabalho e pelo orçamento, não pela moda.",
      outcome: "Um código que outro programador consegue retomar, numa plataforma que continuará suportada dentro de cinco anos.",
      items: [
        "Gestão de Redes Sociais",
        "Desenvolvimento WooCommerce",
        "Desenvolvimento Magento",
        "Desenvolvimento Next.js",
        "Desenvolvimento React",
        "Desenvolvimento Vue.js",
        "Desenvolvimento Node",
        "Desenvolvimento Express.js",
        "Desenvolvimento Laravel",
        "Desenvolvimento PHP",
        "Desenvolvimento Python",
        "Apps Flutter",
        "Apps React Native",
      ],
    },
    {
      group: "UX & design de produto",
      desc: "Desenhamos o percurso da pessoa dentro do produto antes de alguém escrever código.",
      outcome: "Ecrãs testados com utilizadores reais e um sistema de design que a próxima funcionalidade reutiliza.",
      items: [
        "Design de interface (UI)",
        "Arquitectura de informação",
        "Personas",
        "Experiência do utilizador",
        "Testes com utilizadores",
        "Acessibilidade",
        "Prototipagem",
        "Sistemas de design",
        "Estratégia de conteúdos",
      ],
    },
    {
      group: "Gestão de anúncios",
      desc: "Pesquisa paga e display geridos como um investimento com retorno reportado, não como uma mensalidade.",
      outcome: "Um custo por contacto com que consegue planear orçamento, e os dados para o defender.",
      items: [
        "Gestão de Google Ads",
        "Publicidade pay per click (PPC)",
        "Google Display",
        "Google Performance Max",
        "Campanhas de remarketing",
        "Anúncios de pesquisa paga",
        "Bing & Yahoo pay per click",
        "Publicidade mobile",
        "Google Shopping / PLAs",
        "Gestão de feed de produtos",
        "Publicidade programática",
        "PPC multilingue",
        "Auditoria de PPC",
        "Publicidade Amazon",
        "Google Grants",
      ],
    },
    {
      group: "Publicidade em redes sociais",
      detailRoute: "smm",
      desc: "Presença e alcance pago nas plataformas que o seu público abre todos os dias.",
      outcome: "Audiências que crescem com intenção e criativos que merecem o lugar no feed.",
      items: [
        "Gestão de redes sociais",
        "Publicidade Facebook",
        "Publicidade Instagram",
        "Publicidade LinkedIn",
        "Publicidade TikTok",
        "Publicidade YouTube",
        "Publicidade X (Twitter)",
        "Publicidade Snapchat",
        "WhatsApp Business",
        "Coordenação de influenciadores",
      ],
    },
    {
      group: "Optimização para motores de busca",
      desc: "Tornamos o negócio encontrável no momento em que alguém está a procurar.",
      outcome: "Tráfego constante e não pago nas pesquisas que importam, e um site tecnicamente limpo para o manter.",
      items: [
        "Optimização para motores de busca",
        "Pesquisa de palavras-chave",
        "Auditoria de SEO",
        "SEO técnico",
        "Redacção de conteúdos",
        "Marketing de conteúdos",
        "Optimização de e-commerce",
        "SEO local",
        "Compatibilidade de browsers",
        "Implementação de acessibilidade",
        "Marcação schema",
        "SEO para organizações sociais",
      ],
    },
    {
      group: "Medição & análise",
      desc: "A medição montada primeiro, para que cada decisão seguinte seja tomada com evidência.",
      outcome: "Um painel em que a liderança confia e uma resposta clara sobre o retorno de cada canal.",
      items: [
        "Configuração de Google Analytics",
        "Google Tag Manager",
        "Medição de websites",
        "Medição de conversões",
        "Optimização de conversão",
        "Testes A/B",
        "Mapas de calor",
        "Relatórios e dashboards",
        "Integração de campanhas multiplataforma",
        "Microsites",
        "Newsletter HTML",
        "Email marketing",
      ],
    },
    {
      dup: true,
      group: "Tecnologia & soluções",
      items: [
        "Consultoria em soluções digitais",
        "Integração de IA",
        "Fluxos de automação",
        "Implementação de CRM",
        "Integração de pagamentos",
        "Integração e-commerce",
        "Ferramentas internas",
        "Integração de sistemas",
        "Documentação técnica",
        "Desenvolvimento de landing pages",
        "Automação de processos",
        "Optimização da presença online",
      ],
    },
    {
      group: "Serviços de marketing com IA",
      desc: "Usamos IA onde ela retira trabalho que uma pessoa não deveria estar a fazer, qualificar leads, responder à mesma pergunta, escrever a primeira versão.",
      outcome: "Horas devolvidas à equipa todas as semanas e um tempo de resposta que a concorrência não iguala contratando.",
      items: [
        "Automação com IA",
        "Desenvolvimento de chatbots com IA",
        "Desenvolvimento de agentes de IA",
        "Agentes de voz / recepcionistas com IA",
        "Geração de leads com IA",
        "Qualificação e nutrição de leads com IA",
        "Marcação de reuniões com IA",
        "Email marketing e prospecção com IA",
        "Integração e automação de CRM com IA",
        "Desenvolvimento de websites com IA",
        "Desenvolvimento de web apps com IA",
        "Criação de conteúdos com IA",
        "Gestão de redes sociais com IA",
        "Publicidade e optimização de anúncios com IA",
        "SEO, AEO e GEO com IA",
      ],
    },
    {
      group: "Criatividade & produção",
      desc: "A camada de ofício, design, vídeo, fotografia e texto produzidos ao nível que a marca promete.",
      outcome: "Peças de campanha prontas para todos os formatos, feitas uma vez e usadas em todo o lado.",
      items: [
        "Design gráfico",
        "Design de logótipo",
        "Criativos de campanha",
        "Rich media e vídeo",
        "Produção de vídeo",
        "Direcção fotográfica",
        "Design de newsletters",
        "Design de stands",
        "Design de folhetos",
        "Brochuras",
        "Copywriting",
      ],
    },
    {
      group: "Desenvolvimento de aplicações",
      desc: "Aplicações móveis e web construídas para a forma como as pessoas usam o telefone aqui, em ecrã pequeno e ligação irregular.",
      outcome: "Uma aplicação nas lojas, medida e sustentável, com um plano para a versão seguinte.",
      items: [
        "Desenvolvimento de aplicações móveis",
        "Aplicações iOS",
        "Aplicações Android",
        "Aplicações multiplataforma (Flutter, React Native)",
        "Progressive web apps",
        "Desenvolvimento de aplicações web",
        "Design de interface e experiência",
        "Desenvolvimento de APIs e backend",
        "Integrações e pagamentos",
        "Submissão nas lojas",
        "Manutenção e actualizações",
        "Analítica e relatórios de erros",
      ],
    },
  ],
  howHeading: "Como trabalhamos",
  howSub: "Uma estratégia cria valor quando se traduz em acção consistente. Por isso a nossa abordagem acompanha o projecto desde a compreensão do desafio até à sua implementação.",
  how: [
    { n: "01", stage: "Diagnóstico", body: "Compreender o negócio, o contexto, os desafios e as oportunidades." },
    { n: "02", stage: "Direcção estratégica", body: "Definir prioridades, posicionamento e linhas de acção." },
    { n: "03", stage: "Estruturação", body: "Transformar a direcção estratégica em planos, mensagens, iniciativas e recursos." },
    { n: "04", stage: "Activação", body: "Coordenar a execução com equipas, parceiros e fornecedores especializados." },
    { n: "05", stage: "Monitorização", body: "Acompanhar a implementação e garantir consistência ao longo do projecto." },
  ],
  howNote: "Quando um projecto exige competências adicionais, coordenamos recursos especializados em produção audiovisual, fotografia, design, conteúdo, campanhas, comunicação digital, websites e landing pages, SEO e tudo o que a execução exigir.",
  contactHeading: "Contacte-nos",
  contactNote: "Respondemos a cada pedido em 10 horas úteis e em 24 horas aos fins de semana e feriados.",
  contactCells: [
    { label: "WhatsApp", value: "+244 936 499 706", href: "https://wa.me/244936499706" },
    { label: "Email", value: "hello@idealisa.co.ao", href: "mailto:hello@idealisa.co.ao" },
    { label: "Escritório", value: "Luanda, Angola", href: "https://maps.google.com/?q=Luanda,+Angola" },
  ],
};

export const servicesContent: Record<Language, ServicesContent> = {
  en,
  "pt-AO": ptAO,
};

/**
 * Mirrors design-reference's `svcBlocks` construction: the 4 pillars first,
 * then every non-duplicate `dir` group, auto-numbered continuing from the
 * pillar count.
 */
export function buildServiceCards(content: ServicesContent) {
  const cards = content.pillars.map((pillar) => ({
    n: pillar.n,
    title: pillar.title,
    desc: pillar.desc as string | undefined,
    items: pillar.includes,
    outcome: pillar.outcome as string | undefined,
    detailRoute: pillar.detailRoute,
  }));
  content.dir
    .filter((group) => !group.dup)
    .forEach((group) => {
      cards.push({
        n: String(cards.length + 1).padStart(2, "0"),
        title: group.group,
        desc: group.desc,
        items: group.items,
        outcome: group.outcome,
        detailRoute: group.detailRoute,
      });
    });
  return cards;
}
